### ISSUE TITLE
可以提供一个非压缩版的css文件吗？

### ISSUE THREAD

**Issue by kingller** [margox/braft-editor#280]
Hi，
我现在引用组件的css时编译css出错，但将`braft-editor/dist/index.css`文件格式化后，再执行没有问题，请问可以再提供下非压缩版本的css吗？感谢

环境如下:
```
import 'braft-editor/dist/index.css';
```
webpack配置：
```
{
       test: /\.css$/,
       use: [MiniCssExtractPlugin.loader, 'css-loader']
}
```
编译时出错信息：
```
ERROR in /Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ReferenceError: window is not defined
    at /Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:355:2
    at /Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:344:46
    at module.exports.aET+.module.exports (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:412:88)
    at Object.Lzxq (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:318:84)
    at __webpack_require__ (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:21:30)
    at /Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:85:18
    at Object.<anonymous> (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/css-loader/index.js!/Users/tina/Documents/gaiaworks/hrone-react/node_modules/braft-editor/dist/index.css:88:10)
    at Module._compile (module.js:652:30)
```

**Comment by margox** [comment]
报错可能是你的loader配置有问题，看看这个 https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/503 ，可能对你有帮助

**Comment by kingller** [comment]
Sorry, my `webpack` is 4， and since `webpack` v4 the `extract-text-webpack-plugin` should not be used for css. Use `mini-css-extract-plugin` instead. How can I fix it?

**Comment by kingller** [comment]
My webpack:
```
'use strict';

import path from 'path';
import webpack from 'webpack';
import merge from 'webpack-merge';
import gitRevision from 'git-revision';
import UglifyJsPlugin from "uglifyjs-webpack-plugin";
import DashboardPlugin from 'webpack-dashboard/plugin';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import OpenBrowserPlugin from 'open-browser-webpack-plugin';
import CleanWebpackPlugin from 'clean-webpack-plugin';
import CopyWebpackPlugin from 'copy-webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import OptimizeCSSAssetsPlugin from "optimize-css-assets-webpack-plugin";

let ROOT_PATH = path.resolve(__dirname);

let args = require('node-args');
let ENV = args.env || 'development';
let isProduction = ENV === 'production';
let TARGET = `${__dirname}/dest`;

const port = 7360;

let alias = require('./webpack.alias.js')(isProduction);

let config = {
    mode: ENV,
    entry: {
        vendor: ['react', 'classnames', 'react-router', 'react-dom']
    },

    resolve: {
        alias: alias,
        extensions: ['.js', '.jsx']
    },

    output: {
        filename: '[name].[hash:8].bundle.js',
        path: TARGET,
        publicPath: undefined,
    },

    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(ENV),
                'DIR_NAME': JSON.stringify(__dirname),
                'DEVTOOLS': JSON.stringify(!isProduction),
                'URL': require('./pages.js').reduce(function(map, page){
                    map[page.name] = JSON.stringify(page.url);
                    return map;
                }, {})
            }
        }),
        new CopyWebpackPlugin([
            {from: 'assets', to: 'assets'}
        ]),
        new MiniCssExtractPlugin({
            filename: "[name].css",
            chunkFilename: '[name].[contenthash:8].css'  // use contenthash *
        }),
        // 通过这个插件，不再使用id作为打包模块的索引，采用文件路径的hash值，便于缓存
        new webpack.HashedModuleIdsPlugin(),
        new webpack.ProvidePlugin({
            $: 'jquery'
        }),
        new webpack.NormalModuleReplacementPlugin(/hrone-react\/node_modules\//, function(resource){
            //去除hrone-react和hrone-static中的重复模块
            let path = resource.request.replace(/^.*\/node_modules/, `${__dirname}/node_modules`);
            if(require('fs').existsSync(path)){
                resource.request = path;
            }
        }),
        new webpack.NormalModuleReplacementPlugin(/node_modules\/moment\/locale\//, function(resource){
            //去除moment.js中除了简体中文和英语以外的其他国际化文案
            //let locale = require('path').parse(resource.request).name;
            resource.request = resource.request.replace(/[\w\-]+\.js$/, 'zh-cn.js');
        })
    ],

    module: {
        rules: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules\/(?!(hrone-react)\/).*|assets/
            },
            {
                test: /\.less$/,
                use: [MiniCssExtractPlugin.loader, 'css-loader', {
                    loader: 'less-loader',
                    options: {
                        strictMath: true,
                    }
                }],
                exclude: /dynamic-theme\.less/,
            },
            {
                test: /\.css$/,
                use: [MiniCssExtractPlugin.loader, 'css-loader'],
            },
            {
                test: require.resolve('lodash'),
                loader: 'expose-loader?_'
            },
            {
                test: require.resolve('moment'),
                loader: 'expose-loader?moment'
            },
            {
                test: /\.(png|jpg|gif)(\?[a-z0-9\-=]+)?$/,
                loader: 'url-loader?limit=8192',
            },
            {
                test: /\.(svg?)(\?[a-z0-9]+)?$/,
                loader: 'url-loader?limit=8192'
            },
            {
                test: /\.(woff(2)?)(\?[a-z0-9]+)?$/,
                loader: 'file-loader'
            }
        ]
    },
    optimization: {
        runtimeChunk: {
            name: 'manifest'
        },
        splitChunks:{
            chunks: 'async',
            minSize: 30000,
            minChunks: 1,
            maxAsyncRequests: 5,
            maxInitialRequests: 3,
            name: false,
            cacheGroups: {
                vendor: {
                    name: 'vendor',
                    chunks: 'initial',
                    priority: -10,
                    reuseExistingChunk: false,
                    test: /node_modules\/(.*)\.js[x]?/
                },
                styles: {
                    name: 'styles',
                    test: /\.(less|css)$/,
                    minChunks: 1,
                    reuseExistingChunk: true,
                    enforce: true
                }
            }
        }
    },
    devtool: 'source-map',
};

function addEntries(){
    let pages = require('./pages.js');
    pages.forEach(function(page){
        let entry = [];
        if(ENV === 'develop'){
            entry = [
                `webpack-dev-server/client?http://localhost:${port}`,
                'webpack/hot/dev-server',
            ];
        }
        entry.push(`${ROOT_PATH}/src/${page.name}.jsx`)
        config.entry[page.name] = entry;

        let plugin = new HtmlWebpackPlugin({
            filename: `${page.name}.html`,
            template: `${ROOT_PATH}/template.ejs`,
            chunks: ['manifest', 'vendor', 'styles', page.name],
            favicon: 'assets/img/favicon.ico',
            name: page.name,
            title: page.title,
            banner: {
                branch: gitRevision('branch'),
                tag: gitRevision('tag'),
                date: new Date().toLocaleString(),
            },
            'THEME_COLOR': ENV==='production'?'/color.less':'./node_modules/hrone-react/dest/color.less',
            'THEME_LESS': ENV==='production'?'/less.min.js':'./node_modules/hrone-react/dest/less.min.js',
        });
        config.plugins.push(plugin);
    });
}
addEntries();

switch(ENV){
    case 'production':
        config = merge(config, {
            optimization: {
                minimizer: [
                    new UglifyJsPlugin({
                        cache: true,
                        parallel: true,
                        sourceMap: true,
                    }),
                    new OptimizeCSSAssetsPlugin({})  // use OptimizeCSSAssetsPlugin
                ]
            },
            plugins: [
                new CleanWebpackPlugin([TARGET])
            ]
        });
        break;

    case 'development':
        config = merge(config, {
            plugins: [
                new DashboardPlugin(),
                new OpenBrowserPlugin({
                    url: `http://localhost:${port}/app`,
                })
            ],
            devtool: '#source-map',
            devServer: {
                host: '0.0.0.0',
                disableHostCheck: true,
                port: port,
                proxy: {
                    '/signin-oauth': {target: 'http://localhost:5006'},
                    '/api/*': {target: 'http://localhost:5006'},
                    '/login': {target: `http://localhost:${port}`, pathRewrite: {'$':'.html'}},
                    '/app'  : {target: `http://localhost:${port}`, pathRewrite: {'$':'.html'}},
                    '/announcement'  : {target: `http://localhost:${port}`, pathRewrite: {'$':'.html'}},
                },
                lazy: false,
                compress: true, //启用gzip压缩
                headers: {
                    'X-Frame-Options': 'SAMEORIGIN',
                    'X-XSS-Protection': '1; mode=block',
                }
            },
        });
        break;
}

export default config;
```

**Comment by margox** [comment]
https://github.com/margox/braft-intro/blob/master/build/webpack.base.js 参考这个，你既然用了webpack4，extract-text-webpack-plugin这个插件就不要用了

**Comment by margox** [comment]
上面那个文件的目录下还有2个文件分别对于开发环境和生产环境的打包配置

**Comment by kingller** [comment]
已经参照您提供的webpack修改，但仍有问题，现在的情况是可以直接使用，但不能在引用的包中引用该css文件

例如：
项目中引用了`hrone-react`，`hrone-react`中引用了`braft-editor/dist/index.css`，这时候编译会报错

报错如下：
```
ERROR in ./node_modules/braft-editor/dist/index.css
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    Error: Didn't get a result from child compiler
        at childCompiler.runAsChild (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/mini-css-extract-plugin/dist/loader.js:128:23)
        at compile (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compiler.js:290:11)
        at hooks.afterCompile.callAsync.err (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compiler.js:547:14)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
        at AsyncSeriesHook.lazyCompileHook (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/Hook.js:154:20)
        at compilation.seal.err (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compiler.js:544:30)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/Hook.js:154:20)
        at hooks.optimizeAssets.callAsync.err (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compilation.js:1296:35)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/Hook.js:154:20)
        at hooks.optimizeChunkAssets.callAsync.err (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compilation.js:1287:32)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/Hook.js:154:20)
        at hooks.additionalAssets.callAsync.err (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/webpack/lib/Compilation.js:1282:36)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tina/Documents/gaiaworks/announcement/public/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

**Comment by kingller** [comment]
如果是直接引用的话，是没有问题的

**Comment by margox** [comment]
你自己google一下相关的错误试试，我这边现在事情太多了，暂时没太多精力来帮你去查询相关问题，而且我也不清楚hrone-react是什么

**Comment by kingller** [comment]
好的，感谢您的帮助。`hrone-react`是我们目前自己写的组件库。

**Comment by margox** [comment]
如果在你们自己的组件库中引入有问题，就先检查一下和普通项目有哪些差异化，感觉应该还是webpack配置的问题

**Comment by kingller** [comment]
在组件库引用`braft-editor/dist/index.css`，组件库执行没有问题；项目中直接引用`braft-editor/dist/index.css`也没有问题；但在项目中使用组件库封装的组件会报错。将该css文件格式化后再引用也没问题。感觉是`mini-css-extract-plugin`解析时有问题。
